"""set nullable to true in recipe model search_id column

Revision ID: 6faa34436061
Revises: 1e6107378237
Create Date: 2026-05-24 17:40:12.506867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6faa34436061'
down_revision: Union[str, Sequence[str], None] = '1e6107378237'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'search_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('searches', 'ingredients',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=1000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('searches', 'ingredients',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('recipes', 'search_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
